### ISSUE TITLE
Torrent Incomplete Download

### ISSUE THREAD

**Issue by ryanmcgillprof** [Itz-fork/Torrent-Aio-Bot-Duplicate#2]
Does your torrent sometimes upload incomplete torrent on google drive?

**Comment by ryanmcgillprof** [comment]
or u updated that error

**Comment by ryanmcgillprof** [comment]
and what changes you made?

**Comment by partiallywritten** [comment]
Sometimes it happens! There are few reasons for it.

- Google Drive Quota limit reached
- Not enough space left on your drive
- Expired token
- Your Team Drive got banned etc.
